baseURL: "https://jiajingan.github.io/"
title: Jackie Gan
paginate: 5
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
minify:
  disableXML: true
languages:
  en:
    languageName: English
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  env: production
  description: 'My internet blog'
  author: Jackie Gan
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  images:
    - papermod-cover.png
  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: '#'
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
  homeInfoParams:
    Title: Jackie Gan
    Content: "Hi this is Jackie.\n- **Jackie** is a senior undergraduate student in Philadelphia.\n- I work on random projects in my free time.\n- Feel free to checkout my Github and connect with me on Linkedin !\n"
  socialIcons:
    - name: github
      url: 'https://github.com/jiajingan'
    - name: linkedin
      url: 'https://www.linkedin.com/in/jiajingan/'
    - name: email
      url: "mailto:jackiegan123@outlook.com"
  editPost:
    URL: 'https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content'
    Text: Suggest Changes
    appendFilePath: true
taxonomies:
  category: categories
  tag: tags
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
